In [3]:
import numpy as np
list=[10,20,30,40,50]
arr=np.array(list)
print("Array=",arr)

Array= [10 20 30 40 50]


In [6]:
import numpy as np
A=np.zeros((2,2))
B=np.ones((1,3))
print("Matrix A is:",A)
print("Matrix B is:",B)

Matrix A is: [[0. 0.]
 [0. 0.]]
Matrix B is: [[1. 1. 1.]]


In [8]:
import numpy as np
a=np.array([1,2,3,4,5])
print("Max of a is:",a.max())
print("Min of a is:",a.min())
print("Mean of a is:",a.mean())

Max of a is: 5
Min of a is: 1
Mean of a is: 3.0


In [16]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Vertically Stacked arrays A and B:\n",np.vstack((A,B)))
print("Horizontally Stacked arrays A and B:\n",np.hstack((A,B)))

Vertically Stacked arrays A and B:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally Stacked arrays A and B:
 [[1 2 5 6]
 [3 4 7 8]]


In [12]:
import numpy as np
arr=np.array([1,2,1,4,3,4,5,2,6,7,1])
print("Unique elements in the array:",np.unique(arr))

Unique elements in the array: [1 2 3 4 5 6 7]


In [15]:
import numpy as np
A=np.random.randint(0,25,size=(5,5))
print("Matrix:\n",A)

Matrix:
 [[ 0  2 15 23 19]
 [11  8 20 20 19]
 [11  0  4 23 21]
 [20  5  0 11  7]
 [ 3 19 21 19  4]]


In [18]:
import numpy as np
A=np.array([[1,2,5],[3,4,6]])
B=np.array([[5,6],[7,8]])
print(A[1,2])
print(B[1,1])

6
8


In [20]:
import pandas as pd
data={
    'Name':['A','B','C'],
    'Id':[1,14,12],
    'Marks':[98,90,89]
}
print("DataFrame:\n",pd.DataFrame(data))


DataFrame:
   Name  Id  Marks
0    A   1     98
1    B  14     90
2    C  12     89


In [21]:
import pandas as pd
data1={
    'Name':['A','B','C'],
    'Id':[1,2,3],
    'Marks':[98,90,89]
}
d1=pd.DataFrame(data1)
data2={
    'Name':['D','E','F'],
    'Id':[4,5,6],
    'Marks':[82,93,90]
}
d2=pd.DataFrame(data2)
print("Concatenated DataFrames:\n",pd.concat([d1,d2],axis=0))

Concatenated DataFrames:
   Name  Id  Marks
0    A   1     98
1    B   2     90
2    C   3     89
0    D   4     82
1    E   5     93
2    F   6     90


In [23]:
import pandas as pd
data1={
    'Marks':[98,90,93],
    'Class1':['A','B','C']
}
data2={
    'Marks':[98,90,93],
    'Class2':['X','Y','Z']
}
d1=pd.DataFrame(data1)
d2=pd.DataFrame(data2)
print("Merged DataFrames:\n",pd.merge(d1,d2,on='Marks'))

Merged DataFrames:
    Marks Class1 Class2
0     98      A      X
1     90      B      Y
2     93      C      Z


In [4]:
import pandas as pd
file_path=r'C:\Users\user\Desktop\data_modified.csv'
df=pd.read_csv(file_path)
print("Data with missing values:\n",df.head())
df['TOTAL DAYS']=df['TOTAL DAYS'].fillna(50)
print("Data after filling missing values:\n",df.head())

Data with missing values:
   NAME  SECTION  TOTAL DAYS   DAYS PRESENT  MARKS RESULT
0    A      1.0        50.0             47     95   PASS
1    B      2.0         NaN             49     99   PASS
2    C      3.0        50.0             50     99   PASS
3    D      NaN         NaN             35     93   PASS
4    E      5.0         NaN             27     86   PASS
Data after filling missing values:
   NAME  SECTION  TOTAL DAYS   DAYS PRESENT  MARKS RESULT
0    A      1.0        50.0             47     95   PASS
1    B      2.0        50.0             49     99   PASS
2    C      3.0        50.0             50     99   PASS
3    D      NaN        50.0             35     93   PASS
4    E      5.0        50.0             27     86   PASS


In [6]:
import pandas as pd
file_path=r'C:\Users\user\Desktop\data_modified.csv'
df=pd.read_csv(file_path)
print("Original Data:\n",df)
df=df.dropna()
print("Data after removing missing values:\n",df)

Original Data:
   NAME  SECTION  TOTAL DAYS   DAYS PRESENT  MARKS RESULT
0    A      1.0        50.0             47     95   PASS
1    B      2.0         NaN             49     99   PASS
2    C      3.0        50.0             50     99   PASS
3    D      NaN         NaN             35     93   PASS
4    E      5.0         NaN             27     86   PASS
Data after removing missing values:
   NAME  SECTION  TOTAL DAYS   DAYS PRESENT  MARKS RESULT
0    A      1.0        50.0             47     95   PASS
2    C      3.0        50.0             50     99   PASS


In [44]:
import pandas as pd
data={
    'Name':['A','B','C'],
    'Id':[1,2,3],
    'Marks':[98,90,89]
}
df = pd.DataFrame(data)
df.to_excel('output.xlsx', index=False)
print("DataFrame exported to Excel file 'output.xlsx'")


DataFrame exported to Excel file 'output.xlsx'


In [18]:
import pandas as pd
data={
    'Name':['A','B','C'],
    'Id':[1,2,3],
    'Marks':[98,90,89]
}
df = pd.DataFrame(data)
print("Original Data:\n",df)
print("Filtered Data:\n",df[df['Marks']>90])

Original Data:
   Name  Id  Marks
0    A   1     98
1    B   2     90
2    C   3     89
Filtered Data:
   Name  Id  Marks
0    A   1     98


### **Before Debugging**

In [47]:
Code:

import numpy as np
import pandas as pd
import random

def generate_random_number(min_num, max_num):
    num = random.randint(min_num, max_num)
    print("Random number is: " + num)

def calc_average(num_list):
    total = sum(num_list)
    return total / lenght(num_list)

def check_prime(start, end):
    prime_list = []
    for i in range(start, end):
        if i % 2 == 0:
            prime_list.append(i)
    return prime_list

def load_data(filepath):
    data = pd.read_csv(filepath)
    return data

def main():
    num_list = [10, 20, 30, "forty", 50]
    print("The average is: ", calc_average(num_list))
    print("Prime numbers: ", check_prime(1, 10))

    file_path = "data.csv"
    data = load_data(file_path)
    print("Data loaded: ", data)

    random_num = generate_random_number(1, 100)
    print("Generated Random Number: ", random_num)

    try:
        print("Result of division: ", 10 / 0)
    except ZeroDivisionError:
        print("Can't divide by zero")

    numbers = [x for x in range(100) if x % 3 == 0 and x % 5 == 0]
    print("Numbers divisible by 3 and 5 are: ", numbers)

    undefined_function_call()

main()


SyntaxError: invalid syntax (<ipython-input-47-c62dec7d8889>, line 1)

**After Debugging**
1.Corrected string concatenation issue in generate_random_number.
2.Fixed incorrect function name lenght → len in calc_average.
3.Handled non-numeric values in calc_average.
4.Fixed prime number logic in check_prime.
5.Handled missing file errors in load_data.
6.Ensured proper function usage when calling generate_random_number.
7.Removed the undefined function call to prevent crashes.

In [48]:
import numpy as np
import pandas as pd
import random

def generate_random_number(min_num, max_num):
    num = random.randint(min_num, max_num)
    print("Random number is: " + str(num))
    return num

def calc_average(num_list):
    # Ensure all elements are numbers
    filtered_list = [x for x in num_list if isinstance(x, (int, float))]
    if not filtered_list:
        return "Error: No valid numbers in list"

    total = sum(filtered_list)
    return total / len(filtered_list)

def check_prime(start, end):
    prime_list = []
    for num in range(start, end + 1):
        if num > 1:
            is_prime = True
            for i in range(2, int(num ** 0.5) + 1):
                if num % i == 0:
                    is_prime = False
                    break
            if is_prime:
                prime_list.append(num)
    return prime_list

def load_data(filepath):
    try:
        data = pd.read_csv(filepath)
        return data
    except FileNotFoundError:
        print("Error: File not found.")
        return None

def main():
    num_list = [10, 20, 30, "forty", 50]
    print("The average is: ", calc_average(num_list))

    print("Prime numbers: ", check_prime(1, 10))

    file_path = "data.csv"
    data = load_data(file_path)
    if data is not None:
        print("Data loaded: ", data)

    random_num = generate_random_number(1, 100)
    print("Generated Random Number: ", random_num)

    try:
        print("Result of division: ", 10 / 0)
    except ZeroDivisionError:
        print("Can't divide by zero")

    numbers = [x for x in range(100) if x % 3 == 0 and x % 5 == 0]
    print("Numbers divisible by 3 and 5 are: ", numbers)

    # Removed the undefined function call
    # undefined_function_call()

main()


The average is:  27.5
Prime numbers:  [2, 3, 5, 7]
Error: File not found.
Random number is: 76
Generated Random Number:  76
Can't divide by zero
Numbers divisible by 3 and 5 are:  [0, 15, 30, 45, 60, 75, 90]
